name: Front Test

on:
  pull_request:
    branches: [main]
    types:
      - opened
      - synchronize
      - reopened
    paths:
      - "webapp/nextjs/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-changes:
    name: Check Frontend Changes
    runs-on: ubuntu-latest
    outputs:
      has_changes: ${{ steps.filter.outputs.frontend }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Check for frontend file changes
        id: filter
        uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
        with:
          filters: |
            frontend:
              - 'webapp/nextjs/**'

  test:
    name: Run Frontend Tests
    needs: check-changes
    if: needs.check-changes.outputs.has_changes == 'true'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: webapp/nextjs

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up Node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: webapp/nextjs/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Type check
        run: npm run typecheck

      - name: Run Build
        run: npm run build

#      - name: Run Tests
#        run: npm run test
